apiVersion: v1
kind: Service
metadata:
  name: ai-nginx-app
  namespace: ai-nginx-demo
  labels:
    app: ai-nginx-app
spec:
  selector:
    app: ai-nginx-app
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
